version: '3.3'

services:

  swag:
    image: linuxserver/swag
    container_name: swag
    depends_on:
      - wordpress
    volumes:
      - ./config:/config
      - ./default:/config/nginx/site-confs/default
    environment:
      - EMAIL=${EMAIL}
      - URL=${URL}
      - VALIDATION=http
      - TZ=Europe/Madrid
      - PUID=500
      - PGID=500
    ports:
      - "443:443"
      - "80:80"

  wordpress:
    image: arm64v8/wordpress:php8.1
    container_name: wordpress
    hostname: wordpress
    depends_on:
      - db
    restart: always
    #    ports:
    #  - "8080:80"
    volumes:
      - /opt/wp-content:/var/www/html/wp-content
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_MEMORY_LIMIT', '96M' );

  db:
    image: mysql/mysql-server:8.0-aarch64
    container_name: db
    #volumes:
    #  - /var/lib/mysql:/var/lib/mysql
    restart: always
    #ports:
    #  - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
